/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw2_template;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class hw2Test {
    // Tests here
}
