/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pa1_template;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class pa1Test {
    // Tests here
}
