/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw2_template;

public class hw2 {
    public static void main(String[] args) {
        SortArgParser parser = new SortArgParser(args);
        int[] ints = parser.getInts();
        String alg = parser.getAlg();

        System.out.println(alg);
        if (ints == null) {return;}
        for (int j = 0; j < ints.length; j++) {
            System.out.println(ints[j]);
        }
    }
}
